"""Проверяет границы подсчёта и реальные результаты cloc на маленьком репозитории."""

import importlib.util
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest.mock import patch


SPEC = importlib.util.spec_from_file_location(
    "code_report", Path(__file__).with_name("code-report.py"),
)
REPORT = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(REPORT)


class CodeReportTest(unittest.TestCase):
    """Фикстуры не зависят от размера приложения и не меняют рабочую папку."""

    def test_scope_and_counts(self):
        """Не считаем тесты/сборки; сохраняем дубликаты, URL и локальные изменения."""
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary).resolve()
            subprocess.run(["git", "init", "-q", str(root)], check=True)
            go = '// Комментарий\npackage main\n\nvar url = "https://example.com" // Хвост\n'
            fixtures = {
                ".gitignore": "ui/src/ignored.ts\n",
                "cmd/lawa/main.go": go,
                "internal/service/copy.go": go,
                "internal/service/empty.go": "",
                "ui/src/App.tsx": '// Комментарий\nexport const App = () => <a href="https://example.com">Hi</a>;\n',
                "ui/src/styles.css": '/* Комментарий */\na { color: red; }\n',
                "ui/index.html": '<!-- Комментарий -->\n<div>Hi</div>\n',
                "internal/service/main_test.go": go,
                "internal/service/testdata/sample.go": go,
                "internal/service/generated.go": '// Code generated by tool. DO NOT EDIT.\n' + go,
                "internal/vendor/helper.go": go,
                "internal/dashboard/web/ui/bundle.js": "const x = 1;\n",
                "ui/src/App.test.tsx": "const x = 1;\n",
                "ui/src/test-setup.ts": "const x = 1;\n",
                "ui/src/ignored.ts": "const x = 1;\n",
                "ui/src/types.generated.ts": "const x = 1;\n",
                "ui/src/generated-client.ts": "// @generated\nconst x = 1;\n",
                "ui/src/__tests__/helper.ts": "const x = 1;\n",
                "ui/node_modules/library/index.js": "const x = 1;\n",
                "scripts/helper.go": go,
                "assets/landing.js": "const x = 1;\n",
                "ui/vite.config.ts": "const x = 1;\n",
            }
            for name, content in fixtures.items():
                path = root / name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
            deleted = root / "internal/service/deleted.go"
            deleted.write_text(go, encoding="utf-8")
            subprocess.run(["git", "add", "internal/service/deleted.go"], cwd=root, check=True)
            deleted.unlink()
            (root / "internal/service/link.go").symlink_to(root / "cmd/lawa/main.go")
            selected = REPORT.source_files(root)
            self.assertEqual(set(selected), {
                "cmd/lawa/main.go", "internal/service/copy.go", "internal/service/empty.go",
                "ui/src/App.tsx", "ui/src/styles.css", "ui/index.html",
            })
            rows = {row["path"]: row for row in REPORT.count_files(root, selected)}
            self.assertEqual(sum(row["code"] for row in rows.values()), 7)
            self.assertEqual(sum(row["comment"] for row in rows.values()), 5)
            self.assertEqual(sum(row["blank"] for row in rows.values()), 2)
            self.assertEqual(rows["internal/service/empty.go"]["code"], 0)

    def test_missing_dependency(self):
        """Без cloc нужна понятная команда установки, а не пустой успешный отчёт."""
        with patch.object(REPORT.shutil, "which", return_value=None):
            with self.assertRaisesRegex(ValueError, "brew install cloc"):
                REPORT.count_files(Path.cwd(), {"cmd/lawa/main.go": REPORT.PARTS[0]})

    def test_incomplete_report(self):
        """Пропуск непустого файла внешним счётчиком нельзя выдавать за ноль строк."""
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            (root / "main.go").write_text("package main\n", encoding="utf-8")
            result = subprocess.CompletedProcess([], 0, stdout="{}", stderr="")
            with patch.object(REPORT.shutil, "which", return_value="cloc"):
                with patch.object(REPORT.subprocess, "run", return_value=result):
                    with self.assertRaisesRegex(ValueError, "не посчитал файл"):
                        REPORT.count_files(root, {"main.go": REPORT.PARTS[0]})


if __name__ == "__main__":
    unittest.main()
